Update MauticInstaller to allow plugins & themes
composer/installers pull request #484
Opened 2021-03-26 14:16 UTC by nickveenhof

Update MauticInstaller to allow plugins & themes with custom directory names - Please do not merge yet - Still verifying

2021-04-05 08:35 UTC, niksamokhvalov requested changes
Update tests, please.

2021-04-23 20:30 UTC, nickveenhof commented
Tests added - please re-review. Thanks!

2021-04-26 06:26 UTC, niksamokhvalov approved these changes

2021-04-26 06:29 UTC, niksamokhvalov commented
https://github.com/composer/installers/pull/484/checks?check_run_id=2435477260
https://github.com/composer/installers/pull/484/checks?check_run_id=2435477049

These checks is failing. Fix it, please.

2021-04-27 11:02 UTC, nickveenhof commented
Fixed the failing tests, was only not able to reproduce the PHP 5.3 test locally but I think I fixed it due to PHP 7 array syntaxes. Tests still work and phpstan is now also happy

2021-04-28 06:35 UTC, niksamokhvalov approved these changes

2021-04-28 06:35 UTC, merged